spring:
  application:
    name: taskmaster
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmaster
    username: taskmaster
    password: taskmaster
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect