spring:
  application:
    name: taskmaster
  datasource:
    url: jdbc:postgresql://db.logvonbnbwoffadgckkt.supabase.co:5432/postgres
    username: postgres
    password: "OSCdrdfmc100$" # Mantenha as aspas duplas se tiver caracteres especiais
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect